Rails:
  Enabled: true

Documentation:
  Enabled: false

LineLength:
  Max: 120

MethodLength:
  Max: 20

FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Exclude:
    - bin/*
    - db/schema.rb
